spring:
  profiles: development

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/ace_admin?autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update



